# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazes', '0004_auto_20171005_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='vertical_path_width',
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=17),
        ),
    ]
